# -*- coding: utf-8 -*-
"""UrduFakeNews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12SBVwRw-QSycbSkf3_5FX_jPKI9iwG6p

**Installing Dependencies**
"""

!pip install pandas numpy torch matplotlib seaborn scikit-learn transformers datasets evaluate accelerate openpyxl

"""**Importing Dependencies**"""

import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)

from datasets import Dataset
from evaluate import load

import random
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

"""**Initialize Phases (Setup)**"""

dfA = pd.read_csv('/content/Combined .csv')

dfB = pd.read_excel('/content/Notri-Fact_Real_Unreal_Urdu_NEWS.xlsx')

dfA.head()

dfA.shape

dfA.info()

dfB.head()

dfB.shape

dfB.info()

dfA['Label'] = dfA['Label'].astype(str).str.strip().str.upper()
dfA['Label'].value_counts()

dfA = dfA[~dfA['Label'].isin(['NAN', 'LABEL'])]
dfA['Label'].value_counts()

dfA['Label'].value_counts().plot(kind = 'bar', color = ['magenta', 'pink'])

dfA['Label'].value_counts()

dfB['Label'].value_counts().plot(kind = 'bar', color = ['steelblue', 'yellow'])

dfB['Label'].value_counts()

overlap_rate = dfB.apply(
      lambda r: str(r["Headline"])[:30] in str(r["News_Text"]),axis=1).mean()
print(f"Headline-in-body overlap rate: {overlap_rate:.3f}")

"""### Standardizing and Combining Datasets"""

dfA_processed = dfA[['News Items', 'Label']].copy()
dfA_processed.rename(columns={'News Items': 'News'}, inplace=True)
dfA_processed['Label'] = dfA_processed['Label'].map({'FAKE': 0, 'TRUE': 1}).astype(int)

dfB_processed = dfB[['News_Text', 'Label', 'News_length']].copy()
dfB_processed.rename(columns={'News_Text': 'News'}, inplace=True)
dfB_processed['Label'] = dfB_processed['Label'].map({'Unreal': 0, 'Real': 1}).astype(int)

df_combined = pd.concat([dfA_processed, dfB_processed], ignore_index=True)

df_shuffled = df_combined.sample(frac=1, random_state=SEED).reset_index(drop=True)

print("df_shuffled initialized.")

df_shuffled = df_shuffled.drop_duplicates()

print(f"Number of duplicated rows after dropping: {df_shuffled.duplicated().sum()}")
display(df_shuffled.head())

"""### Word Count Analysis"""

df_shuffled['word_count'] = df_shuffled['News'].astype(str).apply(lambda x: len(x.split()))

print("DataFrame with 'word_count' column:")
display(df_shuffled.head())

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df_shuffled[df_shuffled['Label'] == 0]['word_count'], bins=50, color='red', kde=True)
plt.title('Word Count Distribution for Fake News')
plt.xlabel('Word Count')
plt.ylabel('Frequency')

plt.subplot(1, 2, 2)
sns.histplot(df_shuffled[df_shuffled['Label'] == 1]['word_count'], bins=50, color='blue', kde=True)
plt.title('Word Count Distribution for Real News')
plt.xlabel('Word Count')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

print("Summary statistics for word counts per label:")
display(df_shuffled.groupby('Label')['word_count'].describe())

df_a = df_shuffled[df_shuffled['News_length'].isna()][['News', 'Label']].copy()
df_b = df_shuffled[df_shuffled['News_length'].notna()][['News', 'Label']].copy()

df_a = df_a.rename(columns={'News': 'text', 'Label': 'label'})
df_b = df_b.rename(columns={'News': 'text', 'Label': 'label'})

df_a['source'] = 'ax_to_grind'
df_b['source'] = 'notri_fact'

df_a = df_a.reset_index(drop=True)
df_b = df_b.reset_index(drop=True)

print("df_a shape:", df_a.shape)
print("df_b shape:", df_b.shape)
print("df_a labels:", df_a['label'].value_counts().to_dict())
print("df_b labels:", df_b['label'].value_counts().to_dict())

overlap = set(df_a['text'].str[:100]) & set(df_b['text'].str[:100])
print(f"Overlapping articles: {len(overlap)}")
assert len(overlap) == 0, "Datasets overlap - cross-domain experiments are contaminated!"

"""**Transformers Setup**"""

df_a['text'] = df_a['text'].astype(str).str.strip()
df_b['text'] = df_b['text'].astype(str).str.strip()

df_a = df_a[df_a['text'].str.len() > 0].reset_index(drop=True)
df_b = df_b[df_b['text'].str.len() > 0].reset_index(drop=True)

print("df_a:", df_a.shape)
print("df_b:", df_b.shape)

modelName = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(modelName)
print("Tokenizer initialized.", modelName)

sample_texts = df_a['text'].sample(500, random_state=42).tolist()
lengths = [len(tokenizer(t)['input_ids']) for t in sample_texts]

print(f"Mean:     {np.mean(lengths):.0f}")
print(f"Median:   {np.median(lengths):.0f}")
print(f"90th pct: {np.percentile(lengths, 90):.0f}")
print(f"95th pct: {np.percentile(lengths, 95):.0f}")
print(f"99th pct: {np.percentile(lengths, 99):.0f}")

MAX_LENGTH = 256
print(f"\nUsing MAX_LENGTH = {MAX_LENGTH}")

train_a, test_a = train_test_split(
    df_a,
    test_size=0.2,
    random_state=SEED,
    stratify=df_a['label']
)

print("Train size:", len(train_a))
print("Test size: ", len(test_a))
print("Train label distribution:", train_a['label'].value_counts().to_dict())
print("Test label distribution: ", test_a['label'].value_counts().to_dict())

def tokenize_fn(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=MAX_LENGTH
    )

from datasets import Dataset

train_ds_a = Dataset.from_pandas(train_a[['text', 'label']].reset_index(drop=True))
test_ds_a  = Dataset.from_pandas(test_a[['text', 'label']].reset_index(drop=True))

train_ds_a = train_ds_a.map(tokenize_fn, batched=True)
test_ds_a  = test_ds_a.map(tokenize_fn, batched=True)

train_ds_a.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
test_ds_a.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

print("Tokenization done")
print("Train:", train_ds_a)
print("Test: ", test_ds_a)

from evaluate import load as load_metric

accuracy_metric = load_metric("accuracy")
f1_metric       = load_metric("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy":  accuracy_metric.compute(predictions=predictions, references=labels)["accuracy"],
        "f1":        f1_metric.compute(predictions=predictions, references=labels)["f1"],
    }

from transformers import TrainingArguments

training_args_1 = TrainingArguments(
    output_dir="./exp1_ax_to_grind",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    seed=SEED,
    logging_steps=50,
)

from transformers import AutoModelForSequenceClassification, Trainer, DataCollatorWithPadding

model_1 = AutoModelForSequenceClassification.from_pretrained(
    modelName,
    num_labels=2
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer_1 = Trainer(
    model=model_1,
    args=training_args_1,
    train_dataset=train_ds_a,
    eval_dataset=test_ds_a,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)
trainer_1.train()

results_1 = trainer_1.evaluate(test_ds_a)
print("Experiment 1: In-domain Ax-to-Grind")
print(results_1)

from google.colab import drive
drive.mount('/content/drive')

trainer_1.save_model('/content/drive/MyDrive/UrduFakeNews/exp1_model')
tokenizer.save_pretrained('/content/drive/MyDrive/UrduFakeNews/exp1_model')

df_a.to_csv('/content/drive/MyDrive/UrduFakeNews/df_a.csv', index=False)
df_b.to_csv('/content/drive/MyDrive/UrduFakeNews/df_b.csv', index=False)