# -*- coding: utf-8 -*-
"""UrduFakeNews2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thie05-XaoLKl80-WRgNbUvp_--8b6eB

**Installing Dependencies**
"""

!pip install pandas numpy torch matplotlib seaborn scikit-learn transformers datasets evaluate accelerate openpyxl

"""**Importing Libraries**"""

import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

from transformers import(
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)

from datasets import Dataset
from evaluate import load

import random
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

"""**Data Importing from Drive**"""

from google.colab import drive
drive.mount('/content/drive')

df_a = pd.read_csv('/content/drive/MyDrive/UrduFakeNews/df_a.csv')
print("df_a head:")
display(df_a.head())

df_b = pd.read_csv('/content/drive/MyDrive/UrduFakeNews/df_b.csv')
print("df_b head:")
display(df_b.head())

model_path = '/content/drive/MyDrive/UrduFakeNews/exp1_model'

tokenizer = AutoTokenizer.from_pretrained(model_path)
print("Tokenizer loaded successfully.")

model = AutoModelForSequenceClassification.from_pretrained(model_path)
model.to(DEVICE)
print("Model loaded successfully and moved to device:", DEVICE)

def tokenize_fn(examples):
    return tokenizer(examples['text'], truncation=True, padding=True)

"""**Training on Dataset B**"""

train_b, test_b = train_test_split(
    df_b,
    test_size=0.2,
    random_state=SEED,
    stratify=df_b['label']
)

print("Train size:", len(train_b))
print("Test size: ", len(test_b))
print("Train label distribution:", train_b['label'].value_counts().to_dict())
print("Test label distribution: ", test_b['label'].value_counts().to_dict())

train_ds_b = Dataset.from_pandas(train_b[['text', 'label']].reset_index(drop=True))
test_ds_b  = Dataset.from_pandas(test_b[['text', 'label']].reset_index(drop=True))

train_ds_b = train_ds_b.map(tokenize_fn, batched=True)
test_ds_b  = test_ds_b.map(tokenize_fn, batched=True)

train_ds_b.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
test_ds_b.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

print("Tokenization done")

training_args_2 = TrainingArguments(
    output_dir="./exp2_notri_fact",
    num_train_epochs=3,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    learning_rate = 2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    seed=SEED,
    logging_steps=50,
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt")
print("Data collator initialized.")

metric = load("f1")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return metric.compute(predictions=predictions, references=labels)

print("Compute metrics function defined.")

model_2 = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=2
)

trainer_2 = Trainer(
    model=model_2,
    args=training_args_2,
    train_dataset=train_ds_b,
    eval_dataset=test_ds_b,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer_2.train()

results_2 = trainer_2.evaluate(test_ds_b)
print("Experiment 2 In-domain Notri-Fact")
for k, v in results_2.items():
    print(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")

"""**Testing of Dataset B on Dataset A**"""

full_ds_b = Dataset.from_pandas(df_b[['text', 'label']].reset_index(drop=True))
full_ds_b = full_ds_b.map(tokenize_fn, batched=True)
full_ds_b.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

trainer_exp3 = Trainer(
    model=model,
    args=TrainingArguments(output_dir="./exp3", per_device_eval_batch_size=16, seed=SEED),
    compute_metrics=compute_metrics,
)

results_3 = trainer_exp3.evaluate(full_ds_b)
print("Experiment 3: Cross-domain A to B (trained on Ax-to-Grind, tested on Notri-Fact)")
for k, v in results_3.items():
    print(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")

preds_3 = trainer_exp3.predict(full_ds_b)
pred_labels = np.argmax(preds_3.predictions, axis=-1)
print("Predicted label distribution:", np.unique(pred_labels, return_counts=True))
print("Actual label distribution:", np.unique(preds_3.label_ids, return_counts=True))

"""**Testing of Dataset A on Dataset B**"""

full_ds_a = Dataset.from_pandas(df_a[['text', 'label']].reset_index(drop=True))
full_ds_a = full_ds_a.map(tokenize_fn, batched=True)
full_ds_a.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

trainer_exp4 = Trainer(
    model=model_2,
    args=TrainingArguments(output_dir="./exp4", per_device_eval_batch_size=16, seed=SEED),
    compute_metrics=compute_metrics,
)

results_4 = trainer_exp4.evaluate(full_ds_a)
print("Experiment 4: Cross-domain B to A (trained on Notri-Fact, tested on Ax-to-Grind)")
for k, v in results_4.items():
    print(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")

"""**Text Preprocessing**"""

!pip install nltk
import nltk
import re
import string

urdu_stopwords = set([
    'کا', 'کی', 'کے', 'میں', 'ہے', 'ہیں', 'نے', 'کو', 'سے', 'پر',
    'اور', 'یہ', 'وہ', 'ایک', 'بھی', 'تو', 'ہو', 'کہ', 'جو', 'اس',
    'اب', 'تھا', 'تھی', 'تھے', 'گا', 'گی', 'گے', 'لیے', 'ان', 'اپنے',
    'ہوئے', 'ہوئی', 'ہونے', 'والے', 'والی', 'والا', 'رہا', 'رہی', 'رہے',
    'جب', 'تب', 'پھر', 'مگر', 'لیکن', 'یا', 'نہیں', 'نہ', 'ہی', 'تک'
])

urdu_punctuation = '،؟؛۔٪'

def clean_text_urdu(text):
    text = str(text)
    text = re.sub(r'[%s]' % re.escape(urdu_punctuation), ' ', text)

    text = re.sub(r'[%s]' % re.escape(string.punctuation), ' ', text)

    text = re.sub(r'[\d۰-۹]', ' ', text)

    text = re.sub(r'\s+', ' ', text).strip()

    words = text.split()
    words = [w for w in words if w not in urdu_stopwords]
    return ' '.join(words)

df_a['text_clean'] = df_a['text'].apply(clean_text_urdu)
df_b['text_clean'] = df_b['text'].apply(clean_text_urdu)

print("Urdu cleaning done.")
print(df_a['text_clean'].head(2))

!pip install arabic_reshaper python-bidi

import arabic_reshaper
from bidi.algorithm import get_display
import matplotlib.font_manager as fm

# Download and install an Arabic font
!wget https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf -O /usr/share/fonts/truetype/noto/NotoSansArabic-Regular.ttf
!fc-cache -f -v

# Configure matplotlib to use the Arabic font
fm.fontManager.addfont('/usr/share/fonts/truetype/noto/NotoSansArabic-Regular.ttf')
plt.rcParams['font.family'] = 'Noto Sans Arabic'
plt.rcParams['font.size'] = 12

print("Arabic rendering libraries installed and matplotlib configured.")

"""### Word Frequency Analysis (Corrected Arabic Rendering)"""

from collections import Counter
import itertools
import arabic_reshaper
from bidi.algorithm import get_display

def plot_word_frequency(df, title):
    all_words = list(itertools.chain.from_iterable(df['text_clean'].apply(lambda x: str(x).split())))
    word_counts = Counter(all_words)
    most_common_words = word_counts.most_common(20)

    words_raw = [word for word, count in most_common_words]
    words_display = [get_display(arabic_reshaper.reshape(word)) for word in words_raw]
    counts = [count for word, count in most_common_words]

    plt.figure(figsize=(12, 6))
    sns.barplot(x=words_display, y=counts, palette='viridis')
    plt.title(get_display(arabic_reshaper.reshape(title)))
    plt.xlabel(get_display(arabic_reshaper.reshape('الكلمات')))
    plt.ylabel(get_display(arabic_reshaper.reshape('التكرار')))
    plt.xticks(rotation=60, ha='right')
    plt.tight_layout()
    plt.show()

plot_word_frequency(df_a, 'Top 20 Most Frequent Words in Dataset A (Cleaned)')
plot_word_frequency(df_b, 'Top 20 Most Frequent Words in Dataset B (Cleaned)')

def plot_text_length_distribution(df, title):
    df['text_length'] = df['text_clean'].apply(lambda x: len(str(x).split()))

    plt.figure(figsize=(10, 6))
    sns.histplot(df['text_length'], bins=50, kde=True, color='skyblue')
    plt.title(title)
    plt.xlabel('Number of Words')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

plot_text_length_distribution(df_a, 'Distribution of Text Lengths in Dataset A')
print('\n')
plot_text_length_distribution(df_b, 'Distribution of Text Lengths in Dataset B')

"""### Label Distribution"""

def plot_label_distribution(df, title):
    label_counts = df['label'].value_counts()
    labels = ['Fake' if i == 1 else 'Real' for i in label_counts.index]

    plt.figure(figsize=(8, 8))
    plt.pie(label_counts, labels=labels, autopct='%1.1f%%', startangle=90, colors=['lightcoral', 'lightgreen'])
    plt.title(title)
    plt.show()

plot_label_distribution(df_a, 'Label Distribution in Dataset A')
print('\n')
plot_label_distribution(df_b, 'Label Distribution in Dataset B')

"""**TF-IDF and ML Models**"""

train_a_tfidf, test_a_tfidf = train_test_split(df_a, test_size=0.2, random_state=SEED, stratify=df_a['label'])

tfidf_a = TfidfVectorizer(max_features=10000)
X_train_a = tfidf_a.fit_transform(train_a_tfidf['text_clean'])
X_test_a  = tfidf_a.transform(test_a_tfidf['text_clean'])
y_train_a = train_a_tfidf['label']
y_test_a  = test_a_tfidf['label']

lr_a = LogisticRegression(max_iter=1000, random_state=SEED)
lr_a.fit(X_train_a, y_train_a)
print("---- TF-IDF + Logistic Regression: Dataset A ----")
print(classification_report(y_test_a, lr_a.predict(X_test_a)))

svm_a = SVC(kernel='linear', random_state=SEED)
svm_a.fit(X_train_a, y_train_a)
print("---- TF-IDF + SVM: Dataset A ----")
print(classification_report(y_test_a, svm_a.predict(X_test_a)))

train_b_tfidf, test_b_tfidf = train_test_split(df_b, test_size=0.2, random_state=SEED, stratify=df_b['label'])

tfidf_b = TfidfVectorizer(max_features=10000)
X_train_b = tfidf_b.fit_transform(train_b_tfidf['text_clean'])
X_test_b  = tfidf_b.transform(test_b_tfidf['text_clean'])
y_train_b = train_b_tfidf['label']
y_test_b  = test_b_tfidf['label']

lr_b = LogisticRegression(max_iter=1000, random_state=SEED)
lr_b.fit(X_train_b, y_train_b)
print("---- TF-IDF + Logistic Regression: Dataset B ----")
print(classification_report(y_test_b, lr_b.predict(X_test_b)))

svm_b = SVC(kernel='linear', random_state=SEED)
svm_b.fit(X_train_b, y_train_b)
print("---- TF-IDF + SVM: Dataset B ----")
print(classification_report(y_test_b, svm_b.predict(X_test_b)))

"""### Confusion Matrices for Traditional ML Models"""

plt.figure(figsize=(8, 6))
cm_lr_a = confusion_matrix(y_test_a, lr_a_preds)
sns.heatmap(cm_lr_a, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix: LR on Dataset A')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

plt.figure(figsize=(8, 6))
cm_svm_a = confusion_matrix(y_test_a, svm_a_preds)
sns.heatmap(cm_svm_a, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix: SVM on Dataset A')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

plt.figure(figsize=(8, 6))
cm_lr_b = confusion_matrix(y_test_b, lr_b_preds)
sns.heatmap(cm_lr_b, annot=True, fmt='d', cmap='Purples',
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix: LR on Dataset B')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

plt.figure(figsize=(8, 6))
cm_svm_b = confusion_matrix(y_test_b, svm_b_preds)
sns.heatmap(cm_svm_b, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix: SVM on Dataset B')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt")

f1_metric = load("f1")
acc_metric = load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(axis=-1)
    f1 = f1_metric.compute(predictions=predictions, references=labels, average="macro")
    acc = acc_metric.compute(predictions=predictions, references=labels)
    return {"f1": f1["f1"], "accuracy": acc["accuracy"]}

def cap_text(text, max_words=50):
    words = str(text).split()
    return ' '.join(words[:max_words])

df_a_capped = df_a.copy()
df_a_capped['text'] = df_a_capped['text'].apply(lambda x: cap_text(x, 50))

train_a_capped, test_a_capped = train_test_split(
    df_a_capped,
    test_size=0.2,
    random_state=SEED,
    stratify=df_a_capped['label']
)

train_ds_a_capped = Dataset.from_pandas(train_a_capped[['text', 'label']].reset_index(drop=True))
test_ds_a_capped  = Dataset.from_pandas(test_a_capped[['text', 'label']].reset_index(drop=True))

train_ds_a_capped = train_ds_a_capped.map(tokenize_fn, batched=True)
test_ds_a_capped  = test_ds_a_capped.map(tokenize_fn, batched=True)

train_ds_a_capped.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
test_ds_a_capped.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

model_a_capped = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=2
)
model_a_capped.to(DEVICE)

training_args_a_capped = TrainingArguments(
    output_dir="./exp_a_capped",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    seed=SEED,
    logging_steps=50,
    report_to="none",
)

trainer_a_capped = Trainer(
    model=model_a_capped,
    args=training_args_a_capped,
    train_dataset=train_ds_a_capped,
    eval_dataset=test_ds_a_capped,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer_a_capped.train()

results_a_capped = trainer_a_capped.evaluate(test_ds_a_capped)
f1_capped = results_a_capped['eval_f1']
print(f"Exp 5 (Capped at 50 words) F1: {f1_capped:.4f}")
print(f"Exp 1 (Full-length)        F1: 0.9287")
print(f"Drop: {0.9287 - f1_capped:.4f}")

labels = ['Full-length', 'Capped at 50 words']
values = [0.9287, f1_capped]

plt.figure(figsize=(8, 6))
sns.barplot(x=labels, y=values, palette='coolwarm')
plt.title('F1 Score Drop After Length Capping: Dataset A')
plt.xlabel('Text Length Strategy')
plt.ylabel('Macro F1 Score')
plt.ylim(0, 1)
for i, v in enumerate(values):
    plt.text(i, v + 0.02, f'{v:.4f}', ha='center', va='bottom')
plt.tight_layout()
plt.show()